
default_platform(:ios)

platform :ios do
  desc "Build for testing"
  lane :build_for_testing do |options|
    scan(build_for_testing: true)
  end

  desc "Run test"
  lane :run_test do |options|
    scan(test_without_building: true)
  end

  desc "Build and tests"
  lane :build_and_tests do |options|
    build_for_testing
    run_test
    send_discord_notification
  end

  
end

