
default_platform(:ios)

discord_url = ENV['DISCORD_URL']

platform :ios do
  desc "Build for testing"
  lane :build_for_testing do
    scan(workspace: './ChatApp/ChatApp.xcworkspace',
    build_for_testing: true)
  end

  desc "Run test"
  lane :run_test do |options|
    scan(workspace: './ChatApp/ChatApp.xcworkspace',
    test_without_building: true)
  end

  desc "Build and run tests"
  lane :build_and_run_test do |options|
    build_for_testing
    run_test
    discord_notifier(
    webhook_url: discord_url,
    title: "Tinkoff Chat CI",
    description: "Build and Tests Success"
  )
  end
end

