name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS : macos11
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Build and run tests
      env:
        SECRETS_URL: ${{ secrets.SECRETS_URL }}
      run: |
        bundle exec fastlane build_and_run_test
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
        severity: info
        details: Build and Tests Success
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      
